[package]
authors = ["Bruno Grieder <bruno.grieder@cosmian.com>", "Théophile BRÉZOT <theophile.brezot@cosmian.com>"]
description = "Crypto lib for pure crypto primitives"
edition = "2021"
license = "MIT/Apache-2.0"
name = "cosmian_crypto_core"
version = "4.0.1"

[lib]
crate-type = ["rlib", "staticlib"]
name = "cosmian_crypto_core"
path = "src/lib.rs"

[dependencies]
aes-gcm = "0.10"
curve25519-dalek = "3.2"
# specify the js feature for the WASM target
getrandom = { version = "0.2", features = ["js"] }
hex = "0.4"
leb128 = "0.2.5"
rand_chacha = "0.3"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
zeroize = "1.5"

[dev-dependencies]
criterion = "0.4"
sha3 = "0.10"

[[bench]]
name = "benches"
harness = false

[profile.bench]
debug = true
