[package]
authors = ["Bruno Grieder <bruno.grieder@cosmian.com>", "Théophile BRÉZOT <theophile.brezot@cosmian.com>"]
description = "Crypto lib for pure crypto primitives"
edition = "2021"
license = "MIT/Apache-2.0"
name = "cosmian_crypto_core"
version = "3.0.0"

[lib]
crate-type = ["cdylib", "rlib"]
name = "cosmian_crypto_core"
path = "src/lib.rs"

[dependencies]
aes-gcm = "0.10"
curve25519-dalek = "3.2"
# specify the js feature for the WASM target
getrandom = { version = "0.2", features = ["js"] }
hex = "0.4"
hkdf = "0.12"
rand_core = { version = "0.6", features = ["std", "getrandom"] }
rand_hc = "0.3"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10"
thiserror = "1.0"
zeroize = "1.5"
