[package]
name = "cosmian_crypto_core"
version = "8.0.0"
authors = [
    "Bruno Grieder <bruno.grieder@cosmian.com>",
    "Théophile BRÉZOT <theophile.brezot@cosmian.com>",
]
edition = "2021"
license = "MIT/Apache-2.0"
description = "Cosmian base cryptographic library"

[lib]
crate-type = ["rlib", "staticlib"]
name = "cosmian_crypto_core"
path = "src/lib.rs"

[dependencies]
aes-gcm = "0.10"
curve25519-dalek = "4.0.0-rc.2"
x25519-dalek = "2.0.0-rc.2"
crypto_box = { version = "0.9.0-rc.0", features = ["seal"] }
# needed to compile into WASM
getrandom = { version = "0.2", features = ["js"] }
leb128 = "0.2"
rand_chacha = "0.3"
tiny-keccak = { version = "2.0.2", features = ["shake"] }
zeroize = "1.5"

[dev-dependencies]
criterion = "0.5"
libc = "0.2"
libsodium-sys-stable = "1.19.28"

[[bench]]
harness = false
name = "benches"

[profile.bench]
debug = true
