---
name: CI checks

on: push

jobs:
  cargo-lint:
    uses: Cosmian/reusable_workflows/.github/workflows/cargo-lint.yml@develop
    with:
      toolchain: stable
  cargo-semver:
    uses: Cosmian/reusable_workflows/.github/workflows/cargo-semver.yml@develop
    with:
      toolchain: stable
  cargo-dry-publish:
    uses: Cosmian/reusable_workflows/.github/workflows/cargo-publish.yml@develop
    with:
      toolchain: stable
      publish: false
  wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --target wasm32-unknown-unknown
  cargo-aes:
    uses: ./.github/workflows/cargo_tests.yml
    with:
      toolchain: stable
      features: --no-default-features --features aes
  cargo-chacha:
    uses: ./.github/workflows/cargo_tests.yml
    with:
      toolchain: stable
      features: --no-default-features --features chacha
  cargo-ecies:
    uses: ./.github/workflows/cargo_tests.yml
    with:
      toolchain: stable
      features: --no-default-features --features ecies
  cargo-curve25519:
    uses: ./.github/workflows/cargo_tests.yml
    with:
      toolchain: stable
      features: --no-default-features --features curve25519
  cargo-set:
    uses: ./.github/workflows/cargo_tests.yml
    with:
      toolchain: stable
      features: --no-default-features --features set
  cargo-blake:
    uses: ./.github/workflows/cargo_tests.yml
    with:
      toolchain: stable
      features: --no-default-features --features blake
  cargo-sha3:
    uses: ./.github/workflows/cargo_tests.yml
    with:
      toolchain: stable
      features: --no-default-features --features sha3

  cargo-publish:
    needs:
      - cargo-lint
      - cargo-semver
      - cargo-dry-publish
      - wasm
    uses: Cosmian/reusable_workflows/.github/workflows/cargo-publish.yml@develop
    if: startsWith(github.ref, 'refs/tags/')
    with:
      toolchain: stable
    secrets: inherit
